### ISSUE TITLE
Tidak bisa push file via Git setelah rename file di Github Repo

### ISSUE THREAD

**Issue by mayasopiie** [mayasopiie/glintstodo#1]
Halo, saya butuh bantuan. Sebelumnya saya punya dua file di repo GitHub. Yang satu 'new.html', satunya lagi 'index.html'. Saya menghapus file 'index.html' lalu mengganti 'new.html' menjadi 'index.html'. Setelah itu, di komputer saya, saya juga ubah file 'new.html' menjadi 'index.html'. Saat push ke repo di Git, saya dapat notif seperti ini
![screenshot from 2018-07-19 15-05-44](https://user-images.githubusercontent.com/9446897/42929806-594021e2-8b65-11e8-9551-972876b6f03f.png)

mohon bantuannya mas. Thank you.

  @mhaidarh
@michaeltamsil

**Comment by mhaidarhanif** [comment]
`git pull` again before `git push`

**Comment by ariebrainware** [comment]
You can also use git feature in Visual Studio Code if you using it 
![screenshot from 2018-07-19 15-22-13](https://user-images.githubusercontent.com/26453961/42930564-8f03f91e-8b67-11e8-86b9-eedc13f74e16.png)

Update, modified and much more listed in side content .

![screenshot from 2018-07-19 15-22-56](https://user-images.githubusercontent.com/26453961/42930612-aa2c358a-8b67-11e8-832c-eb1bad6f0575.png)

If you want to push , type your commit message first and then press Check :heavy_check_mark: and then press [. . .] (more),press pull and press push, wait for a second then type your github username and password.

DONE
Hope this help

**Comment by mayasopiie** [comment]
Okay thanks mas. It worked! @mhaidarh 
Thanks a lot! It will be used when I get the same problem next time @ariebrainware
